services:
    laravel:
        build:
            context: ./vendor/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile-dev
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - "${SAIL_HOST_IP}:${SAIL_HOST_PORT:-8085}:80"
            - '${VITE_PORT:-5175}:${VITE_PORT:-5175}'
            - "${SAIL_HOST_IP}:${PUSHER_PORT:-6001}:6001"
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            QUEUE_CONNECTION: '${QUEUE_CONNECTION:-rabbitmq}'
            RABBITMQ_HOST: '${RABBITMQ_HOST:-rabbitmq}'
            RABBITMQ_PORT: '${RABBITMQ_PORT:-5672}'
            RABBITMQ_USER: '${RABBITMQ_USER:-guest}'
            RABBITMQ_PASSWORD: '${RABBITMQ_PASSWORD:-guest}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            - rabbitmq
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - 'mysql:mysql'
        ports:
            - "${SAIL_HOST_IP}:${PMA_HOST_PORT:-8084}:80"
        environment:
            MYSQL_USERNAME: '${DB_USERNAME}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            PMA_HOST: mysql
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mariadb:10.6.18'
        ports:
            - '${FORWARD_DB_PORT:-3311}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6382}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    rabbitmq:
        image: "rabbitmq:3-management"
        ports:
            - "${SAIL_HOST_IP}:${FORWARD_RABBIT_PORT:-15674}:15672"
            - "15675:15673"
        environment:
            RABBITMQ_DEFAULT_USER: '${RABBITMQ_USER:-guest}'
            RABBITMQ_DEFAULT_PASS: '${RABBITMQ_PASSWORD:-guest}'
        networks:
            - sail

networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
